language: java
services:
- docker

before_install:
- docker build -t carlad/sinatra .
- docker run -d -p 127.0.0.1:80:4567 godeye_backend /bin/sh -c "cd /root/godeye_backend; bundle exec foreman start;"
- docker ps -a
- docker run carlad/sinatra /bin/sh -c "cd /root/godeye_backend; bundle exec rake test"

script:
- bundle exec rake test
install:
- docker build -t godeye_backend .
- docker run -d -p 127.0.0.1:80:80 --name godeye_backend godeye_backend

script:
- docker ps | grep -q godeye_backend